[package]
name = "layer-climb-config"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["lib"]

[dependencies]
######## Workspace dependencies ########
serde = {workspace = true} 
anyhow = {workspace = true} 
url = {workspace = true}