[package]
name = "layer-climb-config"
description = "Config sub-crate for Climb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
######## Local dependencies ########
layer-climb-address = {workspace = true}
######## Workspace dependencies ########
serde = {workspace = true} 
anyhow = {workspace = true} 
url = {workspace = true}
tendermint = {workspace = true}