[package]
name = "layer-climb"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["lib"]

[features]
web = ["layer-climb-address/web"]

# General dependencies
[dependencies]
layer-climb-core = { path = "../layer-climb-core"}
layer-climb-proto = { path = "../layer-climb-proto"}
layer-climb-address = { path = "../layer-climb-address"}
layer-climb-config = { path = "../layer-climb-config"}