[package]
name = "layer-climb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[features]
web = ["layer-climb-address/web"]

# General dependencies
[dependencies]
layer-climb-core = { path = "../layer-climb-core"}
layer-climb-proto = { path = "../layer-climb-proto"}
layer-climb-address = { path = "../layer-climb-address"}
layer-climb-config = { path = "../layer-climb-config"}