[package]
name = "layer-climb"
description = "Climb - A Rust Cosmos Client Library"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[features]
web = ["layer-climb-signer/web"]

# General dependencies
[dependencies]
layer-climb-core = { workspace = true }
layer-climb-proto = { workspace = true }
layer-climb-address = { workspace = true }
layer-climb-config = { workspace = true }
layer-climb-signer = { workspace = true }