[package]
name = "layer-climb-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
######## Local dependencies ########
layer-climb-proto = { path = "../layer-climb-proto"}
layer-climb-address = { path = "../layer-climb-address"}
layer-climb-config = { path = "../layer-climb-config"}

######## Workspace dependencies ########
# General
cfg-if = {workspace = true} 
async-trait = {workspace = true} 

# Error handling
thiserror = {workspace = true}
anyhow = {workspace = true} 

# Binary encoding
hex = {workspace = true} 
base64 = {workspace = true} 

# Logging
tracing = {workspace = true} 
log = {workspace = true}

# Serdeish
toml = {workspace = true} 
serde = {workspace = true} 
serde_json = {workspace = true} 

# Crypto
bip39 = {workspace = true} 

# Networking
reqwest = {workspace = true} 

# Async
futures = {workspace = true} 

# Randomness
rand = {workspace = true} 

# Cosmos
cosmwasm-std = {workspace = true} 
tendermint = {workspace = true} 
tendermint-rpc = {workspace = true} 

# Pool
deadpool = {workspace = true, optional = true}

######## Target-specific dependencies ########
[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic-web-wasm-client = {workspace = true}
getrandom = {version = "0.3", features = ["wasm_js"]}
futures-timer = {version = "3.0.3", default-features = false, features = ["wasm-bindgen"]}
tonic = {version = "0.12", default-features = false}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = "0.3"
futures-timer = {version = "3.0.3", default-features = false}
tonic = {version = "0.12", default-features = false, features = ["transport", "tls-native-roots", "tls-webpki-roots"]}
deadpool = {workspace = true}
tokio = { version = "1", features = ["sync"] } # do not use from workspace which pulls in "full"