[package]
name = "layer-climb-core"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["lib"]

[features]
default = ["binary"]
web = [
    "getrandom/js", 
    "futures-timer/wasm-bindgen",
    "layer-climb-proto/web",
    "layer-climb-address/web",
    "layer-climb-config/web"
]
binary = [
    "tonic/transport", 
    "tonic/tls-native-roots", 
    "tonic/tls-webpki-roots",
    "layer-climb-proto/binary",
    "layer-climb-address/binary",
    "layer-climb-config/binary"
]

[dependencies]
######## Local dependencies ########
layer-climb-proto = { path = "../layer-climb-proto", default-features = false}
layer-climb-address = { path = "../layer-climb-address", default-features = false}
layer-climb-config = { path = "../layer-climb-config", default-features = false}

######## Workspace dependencies ########
# General
cfg-if = {workspace = true} 
async-trait = {workspace = true} 

# Error handling
thiserror = {workspace = true}
anyhow = {workspace = true} 

# Binary encoding
hex = {workspace = true} 
base64 = {workspace = true} 

# Logging
tracing = {workspace = true} 

# Serdeish
toml = {workspace = true} 
serde = {workspace = true} 
serde_json = {workspace = true} 

# Crypto
bip39 = {workspace = true} 

# Networking
reqwest = {workspace = true } 

# Async
futures = {workspace = true} 

# Randomness
rand = {workspace = true} 

# Cosmos
cosmwasm-std = {workspace = true} 
tendermint = {workspace = true} 
tendermint-rpc = {workspace = true} 


######## Featureful dependencies ########
getrandom = "0.2"
futures-timer = {version = "3.0.3", default-features = false}
tonic = {version = "0.12", default-features = false}
tonic-web-wasm-client = {workspace = true}