[package]
name = "layer-climb-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
### Workspace dependencies ###
layer-climb = { workspace = true }
serde = { workspace = true } 
serde_json = {workspace = true} 
anyhow = {workspace = true}
clap = { workspace = true}
futures = {workspace = true}
cosmwasm-std = {workspace = true}
dotenvy = {workspace = true} 
tracing-subscriber = {workspace = true} 
bip39 = {workspace = true}
rand = {workspace = true}
deadpool = {workspace = true}
tokio = {workspace = true}