[package]
name = "layer-climb-cli"
version = "0.3.3"
edition = "2021"
license = "Apache-2.0"

[dependencies]
### Workspace dependencies ###
layer-climb = { workspace = true }
serde = { workspace = true } 
serde_json = {workspace = true} 
anyhow = {workspace = true}
clap = { workspace = true}
futures = {workspace = true}
cosmwasm-std = {workspace = true}
dotenvy = {workspace = true} 
tracing-subscriber = {workspace = true} 
bip39 = {workspace = true}
rand = {workspace = true}
deadpool = {workspace = true}
tokio = {workspace = true}