[package]
name = "layer-climb-proto"
description = "Protobuf sub-crate for Climb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
######## Workspace dependencies ########
# Proto
cosmos-sdk-proto = {workspace = true} 
tendermint-proto = {workspace = true}

# Error handling
thiserror = {workspace = true}
anyhow = {workspace = true} 

######## Target-specific dependencies ########
[target.'cfg(target_arch = "wasm32")'.dependencies]
ibc-proto = {version = "0.51.1", default-features = false, features = ["std", "client"]} 

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ibc-proto = {version = "0.51.1", default-features = false, features = ["std", "client", "transport"]} 
