name: CI Workflow 

on:
  pull_request:
    branches:
      - '**'        # Run tests on any pull request for any branch
  push:
    branches:
      - main        # Run build only when changes are pushed (merged) to `main`

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --manifest-path ./packages/layer-climb/Cargo.toml --all-features --tests -- -D warnings

      - name: cargo test
        run: cargo test --all-features --workspace
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: info
          CLIMB_TEST_MNEMONIC: "session fatigue usage album plunge yard slice bicycle pig fly crack spin abandon dust misery minute orange lava raven sausage pill urge assault drop"
          LOCAL_FAUCET_MNEMONIC: "session fatigue usage album plunge yard slice bicycle pig fly crack spin abandon dust misery minute orange lava raven sausage pill urge assault drop"

  pages_build:
    name: Build Pages 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest' 
      
      - name: Build frontend
        run: trunk build --no-default-features --features dev --release --public-url=https://lay3rlabs.github.io/climb/
        working-directory: ./examples/frontend
        env:
          RUSTFLAGS: "--cfg getrandom_backend=\"wasm_js\""
      
      - name: Copy for 404 redirect
        run: cp ./examples/frontend/dist/index.html ./examples/frontend/dist/404.html

      - name: Build cargo doc
        run: cargo doc --release --no-deps --all-features 
        working-directory: ./packages/layer-climb

      - name: Copy cargo doc 
        run: cp -R ./target/doc ./examples/frontend/dist/doc

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./examples/frontend/dist
  
  pages_deploy:
    name: Deploy Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: pages_build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages